version: "3.8"
networks:
    frontend:
        driver: bridge
        internal: false
    backend:
        driver: bridge
        internal: true
services:
    # DOCKER HUB: https://hub.docker.com/_/composer/
    composer:
        image: composer:2.0.8
        container_name: ${COMPOSE_PROJECT_NAME}-composer
        volumes:
            - ./application-backend:/var/www/html
        working_dir: /var/www/html
        depends_on:
            - php
        networks:
            - frontend

    mysql:
        # DOCKER HUB: https://hub.docker.com/_/mysql/
        container_name: ${COMPOSE_PROJECT_NAME}-mysql
        environment:
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
        healthcheck:
            test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
            timeout: 30s
            interval: 10s
            retries: 10
        image: mysql:8.0.22
        networks:
            - backend
        ports:
            - 127.0.0.1:3306:3306
        volumes:
            - ./docker/tmp/data/mysql:/var/lib/mysql
            - ./docker/setup/phpmyadmin/create_tables.sql:/docker-entrypoint-initdb.d/1.sql
    # DOCKER HUB: https://hub.docker.com/_/node
    node:
        build: ./docker/setup/node
        container_name: ${COMPOSE_PROJECT_NAME}-node
        networks:
            - frontend
        ports:
            - 4200:4200
        volumes:
            - ./application-frontend:/home/node
            - /home/node/node_modules
    nginx:
        # DOCKER HUB: https://hub.docker.com/_/nginx/
        build: ./docker/setup/nginx
        container_name: ${COMPOSE_PROJECT_NAME}-nginx
        depends_on:
            - php
        networks:
            - backend
            - frontend
        ports:
            - "8080:80"
        volumes:
            - ./public:/var/www/public
            - ./docker/tmp/logs/nginx:/var/log/nginx
    php:
        # DOCKER HUB: https://hub.docker.com/_/php/
        build: ./docker/setup/php
        container_name: ${COMPOSE_PROJECT_NAME}-php
        depends_on:
            mysql:
                condition: service_healthy
        networks:
            - backend
        ports:
            - 9000:9000
        volumes:
            - ./application-backend:/var/www
            - ./docker/tmp/logs/php:/var/log/php
    phpmyadmin:
        # DOCKER HUB: https://hub.docker.com/_/phpmyadmin
        container_name: ${COMPOSE_PROJECT_NAME}-phpmyadmin
        depends_on:
            mysql:
                condition: service_healthy
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_USER: "root"
            PMA_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
        image: phpmyadmin:5.0.4-apache
        networks:
            - backend
            - frontend
        ports:
            - 8888:80
