version: "3.8"
networks:
    frontend:
        driver: bridge
        internal: false
    backend:
        driver: bridge
        internal: true
services:
    php7:
        # DOCKER HUB: https://hub.docker.com/_/php/
        build: ./resources/docker/development/php-7.4.33/php
        container_name: lemp-php7
        depends_on:
            mysql:
                condition: service_healthy
        networks:
            - backend
        env_file:
            - docker.env
        volumes:
            - ./:/var/www/html
            - /var/www/html/vendor
    php8:
        # DOCKER HUB: https://hub.docker.com/_/php/
        build: ./resources/docker/development/php-8.3.2/php
        container_name: lemp-php8
        depends_on:
            mysql:
                condition: service_healthy
        networks:
            - backend
        env_file:
            - docker.env
        volumes:
            - ./:/var/www/html
            - /var/www/html/vendor
    nginx:
        # DOCKER HUB: https://hub.docker.com/_/nginx/
        build: ./resources/docker/development/php-dual/nginx
        container_name: lemp-nginx
        depends_on:
            - php7
            - php8
        env_file:
            - docker.env
        networks:
            - backend
            - frontend
        ports:
            - 8080:80
            - 8088:88
        volumes:
            - ./:/var/www/html
            - /var/www/html/vendor
    mysql:
        # DOCKER HUB: https://hub.docker.com/_/mysql/
        build: ./resources/docker/development/php-7.4.33/mysql
        container_name: lemp-mysql
        env_file:
            - docker.env
        healthcheck:
            test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
            timeout: 30s
            interval: 10s
            retries: 10
        command: --default-authentication-plugin=mysql_native_password
        networks:
            - backend
        ports:
            - 3306:3306
    phpmyadmin:
        # DOCKER HUB: https://hub.docker.com/_/phpmyadmin
        container_name: lemp-phpmyadmin
        depends_on:
            mysql:
                condition: service_healthy
        env_file:
            - docker.env
        image: phpmyadmin:5.2.1-apache
        networks:
            - backend
            - frontend
        ports:
            - 8888:80
