version: "3.8"
networks:
    frontend:
        driver: bridge
        internal: false
    backend:
        driver: bridge
        internal: true
services:
    php:
        # DOCKER HUB: https://hub.docker.com/_/php/
        build: ./resources/docker/development/php-8.0.30/php
        container_name: lemp-php
        depends_on:
            mysql:
                condition: service_healthy
        networks:
            - backend
        env_file:
            - 'docker.env'
        ports:
            - 9000:9000
        volumes:
            - ./:/var/www/html
            - /var/www/html/vendor
    nginx:
        # DOCKER HUB: https://hub.docker.com/_/nginx/
        build: ./resources/docker/development/php-8.0.30/nginx
        container_name: lemp-nginx
        depends_on:
            - php
        env_file:
            - 'docker.env'
        networks:
            - backend
            - frontend
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
            - /var/www/html/vendor
    mysql:
        # DOCKER HUB: https://hub.docker.com/_/mysql/
        build: ./resources/docker/development/php-8.0.30/mysql
        container_name: lemp-mysql
        env_file:
            - 'docker.env'
        healthcheck:
            test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
            timeout: 30s
            interval: 10s
            retries: 10
        command: --default-authentication-plugin=mysql_native_password
        networks:
            - backend
        ports:
            - 3306:3306
    phpmyadmin:
        # DOCKER HUB: https://hub.docker.com/_/phpmyadmin
        container_name: lemp-phpmyadmin
        depends_on:
            mysql:
                condition: service_healthy
        env_file:
            - 'docker.env'
        image: phpmyadmin:5.2.1-apache
        networks:
            - backend
            - frontend
        ports:
            - 8888:80
